services:
  server:
    image: itzg/minecraft-server:java17
    tty: true
    stdin_open: true
    ports:
      - 25565:25565/tcp
      - 25565:25565/udp
      - 25575:25575/tcp
    env_file: .env
    environment:
      UID: 3000
      GID: 3000
      TZ: Asia/Bangkok
      EULA: true
      USE_AIKAR_FLAGS: true
      ALLOW_FLIGHT: true
      RCON_PASSWORD: ${RCON_PASSWORD}
      MEMORY: 8G
      TYPE: FTBA
      FTB_MODPACK_ID: 117
    volumes:
      - ada-truenas:/data

volumes:
  ada-truenas:
    driver: local
    driver_opts:
      type: nfs
      o: addr=ada-truenas
      device: :/mnt/main/home/songpola/share/docker/mc-ftb-skies-expert
